# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DropAdd_cpp <- function(dmat, m, time_budget_s, max_iter, max_no_improve, want_trace) {
    .Call(`_MaxMin_DropAdd_cpp`, dmat, m, time_budget_s, max_iter, max_no_improve, want_trace)
}

DropAdd_points_cpp <- function(points, m, time_budget_s, max_iter, max_no_improve, want_trace) {
    .Call(`_MaxMin_DropAdd_points_cpp`, points, m, time_budget_s, max_iter, max_no_improve, want_trace)
}

Grasp_cpp <- function(dmat, m, max_no_improve, max_iter, elite_size, alpha, time_budget_s, progress_cb = NULL) {
    .Call(`_MaxMin_Grasp_cpp`, dmat, m, max_no_improve, max_iter, elite_size, alpha, time_budget_s, progress_cb)
}

IsSymmetric_cpp <- function(d, tol) {
    .Call(`_MaxMin_IsSymmetric_cpp`, d, tol)
}

KCentreCandidates_cpp <- function(d) {
    .Call(`_MaxMin_KCentreCandidates_cpp`, d)
}

KCentreCDSh_cpp <- function(d, k, seed, cand, exhaustive) {
    .Call(`_MaxMin_KCentreCDSh_cpp`, d, k, seed, cand, exhaustive)
}

MaximinFrom_cpp <- function(d, n, first) {
    .Call(`_MaxMin_MaximinFrom_cpp`, d, n, first)
}

MaximinFromPoints_cpp <- function(points, n, first, mask) {
    .Call(`_MaxMin_MaximinFromPoints_cpp`, points, n, first, mask)
}

RowSumsFromPoints_cpp <- function(points) {
    .Call(`_MaxMin_RowSumsFromPoints_cpp`, points)
}

RowSqSumsFromPoints_cpp <- function(points) {
    .Call(`_MaxMin_RowSqSumsFromPoints_cpp`, points)
}

EuclidColFromPoints_cpp <- function(points, col) {
    .Call(`_MaxMin_EuclidColFromPoints_cpp`, points, col)
}

DiameterFromPoints_cpp <- function(points) {
    .Call(`_MaxMin_DiameterFromPoints_cpp`, points)
}

